---
- hosts: workload-generator
  become: true
  tasks:

    - name: Set base playbook directory
      set_fact:
        base_playbook_dir: "{{ playbook_dir | regex_replace('/ansible/mongo/playbook$', '') }}"

    - name: Display base playbook directory
      debug:
        msg: "The base playbook directory is: {{ base_playbook_dir }}"

    - name: Set path to params.json
      set_fact:
        params_json_path: "{{ base_playbook_dir | dirname }}/send_mongo_cfg/params.json"

    - name: Display params.json path
      debug:
        msg: "The path to params.json is: {{ params_json_path }}"


    - name: Copy the file from master to wg1
      copy: src='{{params_json_path}}' dest='{{ wg_ycsb_dir }}'

    - name: Transfer the Python script to target
      copy:
        src: ./scripts/ycsb_metrics_to_json.py
        dest: "{{ wg_ycsb_dir }}"
        mode: '0755'

    - name: Execute the Python script
      command:
        cmd: "python3 ycsb_metrics_to_json.py {{ inventory_hostname }} {{ workload }} {{ operationcount }} {{ threads }}"
      args:
        chdir: "{{ wg_ycsb_dir }}"


