---
- hosts: workload-generator
  become: true
  tasks:
    - name: Transfer the Python script to target
      copy:
        src: ./scripts/merger.py
        dest: "{{ wg_ycsb_dir }}"
        mode: '0755'

    - name: Execute the Python script
      command:
        cmd: "python3 {{ wg_ycsb_dir }}/merger.py {{ inventory_hostname }}"
      args:
        chdir: "{{ wg_ycsb_dir }}"
